Repository Activiti/activiti-cloud-modeling-service, pull requests merged in 2018-12, with the labels that each got.

#113 BeanDefinitionOverrideException in activiti-cloud-modeling
  activiti-cloud-starter-org/src/main/java/org/activiti/cloud/organization/OrganizationSwaggerConfiguration.java
Labels: in progress

#114 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#115 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#117 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#118 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#119 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: updatebot

#120 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: updatebot

#121 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: updatebot

#124 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: updatebot

#125 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: updatebot
