Repository Activiti/activiti-cloud-modeling-service, pull requests merged in 2018-11, with the labels that each got.

#88 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#89 update org.activiti.cloud.process.model:activiti-cloud-process-model-dependencies to 7.0.24
  pom.xml
Labels: updatebot

#91 update org.activiti.cloud.process.model:activiti-cloud-process-model-dependencies to 7.0.25
  pom.xml
Labels: updatebot

#96 2111 Do validation before exporting the application
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/main/java/org/activiti/cloud/services/organization/rest/assembler/ApplicationResourceAssembler.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/mock/MockFactory.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ApplicationControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/service/ApplicationService.java
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/service/ModelService.java
Labels: in progress

#94 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  .updatebot.yml
Labels: enhancement, in progress

#95 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.47
  pom.xml
Labels: in progress, updatebot

#93 update org.activiti.cloud.modeling.build:activiti-cloud-modeling-parent to 7.0.3
  pom.xml
Labels: in progress, updatebot

#92 2001 add json views for models
  activiti-cloud-services-org/activiti-cloud-services-org-api-impl/src/main/java/org/activiti/cloud/organization/api/impl/ModelImpl.java
  activiti-cloud-services-org/activiti-cloud-services-org-api-impl/src/main/java/org/activiti/cloud/organization/api/impl/ModelView.java
  activiti-cloud-services-org/activiti-cloud-services-org-jpa/src/main/java/org/activiti/cloud/services/organization/entity/ModelEntity.java
  activiti-cloud-services-org/activiti-cloud-services-org-jpa/src/main/java/org/activiti/cloud/services/organization/jpa/ApplicationJpaRepository.java
  activiti-cloud-services-org/activiti-cloud-services-org-jpa/src/main/java/org/activiti/cloud/services/organization/jpa/ModelJpaRepository.java
  activiti-cloud-services-org/activiti-cloud-services-org-repository/src/main/java/org/activiti/cloud/organization/repository/ApplicationRepository.java
  activiti-cloud-services-org/activiti-cloud-services-org-repository/src/main/java/org/activiti/cloud/organization/repository/ModelRepository.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/main/java/org/activiti/cloud/services/organization/rest/api/ModelRestApi.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/main/java/org/activiti/cloud/services/organization/rest/assembler/ApplicationResourceAssembler.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/main/java/org/activiti/cloud/services/organization/rest/controller/ModelController.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/mock/MockFactory.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/client/ProcessModelServiceRestClientIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ApplicationControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ModelControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/service/ApplicationService.java
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/service/JsonConverter.java
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/service/JsonConverterConfiguration.java
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/service/ModelService.java
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/service/ModelTypeService.java
Labels: in progress

#97 update org.activiti.cloud.process.model:activiti-cloud-process-model-dependencies to 7.0.26
  pom.xml
Labels: in progress, updatebot

#98 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.49
  pom.xml
Labels: in progress, updatebot

#99 update org.activiti.cloud.process.model:activiti-cloud-process-model-dependencies to 7.0.27
  pom.xml
Labels: in progress, updatebot

#101 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#102 update org.activiti.cloud.process.model:activiti-cloud-process-model-dependencies to 7.0.28
  pom.xml
Labels: in progress, updatebot

#100 Add activiti-cloud-org-dependencies-tests module
  .mergify.yml
  activiti-cloud-org-dependencies/pom.xml
  activiti-cloud-services-org/pom.xml
  activiti-cloud-starter-org/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#103 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#104 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#105 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#106 fix(versions): update Activiti/activiti-cloud-org-service versions
  Jenkinsfile
  pom.xml
Labels: in progress, updatebot

#107 remove bean overriding
  activiti-cloud-starter-org/src/test/resources/application.properties
Labels: in progress

#109 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#110 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot

#111 missed these
  activiti-cloud-services-org/activiti-cloud-services-org-jpa/src/test/resources/application.properties
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/resources/application.properties
Labels: in progress

#112 fix(versions): update Activiti/activiti-cloud-org-service versions
  pom.xml
Labels: in progress, updatebot
