Repository Activiti/activiti-cloud-modeling-service, pull requests merged in 2019-12, with the labels that each got.

#446 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#399 fix(AAE-780): added `@WithMockModelerUser` test security context support
  activiti-cloud-services-org/activiti-cloud-services-org-rest/pom.xml
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/config/OrganizationRestApplication.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ConnectorModelControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ConnectorValidationControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/GenericJsonModelTypeContentUpdateListenerControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/GenericJsonModelTypeControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/GenericJsonModelTypeValidationControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/GenericNonJsonModelTypeContentUpdateListenerControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/GenericNonJsonModelTypeControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/GenericNonJsonModelTypeValidationControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ModelControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ModelValidationControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ProjectControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/security/WithMockModelerUser.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/resources/application.properties
  pom.xml
Labels: bug

#448 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#449 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#450 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#452 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#453 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#454 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#455 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#456 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#459 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#460 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#461 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#462 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#464 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#466 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#467 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#468 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#465 fix(AAE-1187): Remove unused stream dependency from Modeling
  activiti-cloud-services-org/activiti-cloud-services-org-rest/pom.xml
Labels: bug

#469 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#470 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#471 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#472 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#475 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#476 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#477 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#478 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#482 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#483 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#485 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#486 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#487 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#488 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#479 [AAE-1197] The datetime validation error message can be improved to a more user friendly message.
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ModelControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/java/org/activiti/cloud/services/organization/rest/controller/ModelValidationControllerIT.java
  activiti-cloud-services-org/activiti-cloud-services-org-rest/src/test/resources/process-extensions/invalid-datetime-variable-extensions.json
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/java/org/activiti/cloud/services/organization/validation/JsonSchemaModelValidator.java
  activiti-cloud-services-org/activiti-cloud-services-org-service/src/main/resources/schema/process-extensions-schema.json
Labels: enhancement

#489 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#490 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#491 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#493 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#494 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#495 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#497 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#498 fix(versions): update Activiti/activiti-cloud-org-service versions into develop
  pom.xml
Labels: updatebot

#500 fix(versions): update Activiti/activiti-cloud-modeling-service versions into develop
  pom.xml
Labels: updatebot
